### ISSUE TITLE
"Error: Unclosed element `div`" for template that worked with Handlebars

### ISSUE THREAD

**Issue by Kerrick** [tildeio/htmlbars#295]
I have the following template that worked with Handlebars:

```hbs
{{#if disableInteraction}}
  <div class="relative">
{{/if}}
  Lots of stuff here
{{#if disableInteraction}}
  <div class="transparent-absolute-cover"></div>
</div>
{{/if}}
```

This worked great with Handlebars for Ember CLI. However, When trying to compile this using HTMLBars for Ember CLI, I get the following error:

```
Unclosed element `div` (on line 2)
Error: Unclosed element `div` (on line 2).
    at HTMLProcessor.nodeHandlers.Program (/path/to/app/bower_components/ember/ember-template-compiler.js:3385:17)
    at HTMLProcessor.acceptNode (/path/to/app/bower_components/ember/ember-template-compiler.js:3579:43)
    at HTMLProcessor.nodeHandlers.BlockStatement (/path/to/app/bower_components/ember/ember-template-compiler.js:3405:44)
    at HTMLProcessor.acceptNode (/path/to/app/bower_components/ember/ember-template-compiler.js:3579:43)
    at HTMLProcessor.nodeHandlers.Program (/path/to/app/bower_components/ember/ember-template-compiler.js:3375:16)
    at HTMLProcessor.acceptNode (/path/to/app/bower_components/ember/ember-template-compiler.js:3579:43)
    at preprocess (/path/to/app/bower_components/ember/ember-template-compiler.js:3551:55)
    at compileSpec (/path/to/app/bower_components/ember/ember-template-compiler.js:741:17)
    at TemplateCompiler.__exports__.default [as precompile] (/path/to/app/bower_components/ember/ember-template-compiler.js:643:14)
    at TemplateCompiler.processString (/path/to/app/node_modules/ember-cli-htmlbars/index.js:58:38)
```

Is this sort of template no longer supported, or is this a bug in HTMLBars?

**Comment by rwjblue** [comment]
> This worked great with HTMLBars for Ember CLI. However, When trying to compile this using HTMLBars for Ember CLI, I get the following error:

That confuses me.  Do you mean that it worked fine with Handlebars, but not HTMLBars?

**Comment by rwjblue** [comment]
Even in Handlebars, this would not have worked properly (with bindings and whatnot).  See [this JSBin](http://emberjs.jsbin.com/rwjblue/301/edit?html,js,output) using 1.9.0 that shows what I mean.  When you check the `isEnabled` checkbox, it adds the `div`'s, but they are not updated properly (meaning `Other Stuff` is not in the right place).

**Comment by mmun** [comment]
@Kerrick Correct, it is not supported. You can think of block helpers like the new `<template>` tag.

**Comment by Kerrick** [comment]
> That confuses me. Do you mean that it worked fine with Handlebars, but not HTMLBars?

Sorry, I did mean that.

**Comment by Kerrick** [comment]
> Even in Handlebars, this would not have worked properly (with bindings and whatnot). See this JSBin using 1.9.0 that shows what I mean. When you check the isEnabled checkbox, it adds the div's, but they are not updated properly (meaning Other Stuff is not in the right place).

Interesting, it looks like this never _actually_ worked and was always silently failing. Thanks for clarifying!

**Comment by TheRedDevil** [comment]
I understand that this is a feature, but does anybody know how we can render nested divs using HTMLbars, or is there any other tempating engine compatible with Ember?

**Comment by pvchaumier** [comment]
Any news on how this could work without having to duplicate code ? Great work on Ember by the way :smile:
