### ISSUE TITLE
Text misinterpreted as `Unclosed element `

### ISSUE THREAD

**Issue by bndw** [tildeio/htmlbars#299]
Emberjs: v1.10.0
Ember-cli: v0.1.15

In the following template snippet, the `<--` arrow is misinterpreted as an HTML element.

```
{{#link-to "tornado"}}
    <p> <-- Go Back</p>
{{/link-to}}
```

```
bdw ~/projects/tornado/src/browser ember server
version: 0.1.15
Could not find watchman, falling back to NodeWatcher for file system events
Livereload server on port 35729
Serving on http://0.0.0.0:4200/
File: browser/pods/tornado/one/template.hbs
Unclosed element `go` (on line 6).
Error: Unclosed element `go` (on line 6).
    at HTMLProcessor.nodeHandlers.Program (/Users/bdw/projects/tornado/src/browser/bower_components/ember/ember-template-compiler.js:3385:17)
    at HTMLProcessor.acceptNode (/Users/bdw/projects/tornado/src/browser/bower_components/ember/ember-template-compiler.js:3579:43)
    at HTMLProcessor.nodeHandlers.BlockStatement (/Users/bdw/projects/tornado/src/browser/bower_components/ember/ember-template-compiler.js:3405:44)
    at HTMLProcessor.acceptNode (/Users/bdw/projects/tornado/src/browser/bower_components/ember/ember-template-compiler.js:3579:43)
    at HTMLProcessor.nodeHandlers.Program (/Users/bdw/projects/tornado/src/browser/bower_components/ember/ember-template-compiler.js:3375:16)
    at HTMLProcessor.acceptNode (/Users/bdw/projects/tornado/src/browser/bower_components/ember/ember-template-compiler.js:3579:43)
    at preprocess (/Users/bdw/projects/tornado/src/browser/bower_components/ember/ember-template-compiler.js:3551:55)
    at compileSpec (/Users/bdw/projects/tornado/src/browser/bower_components/ember/ember-template-compiler.js:741:17)
    at TemplateCompiler.__exports__.default [as precompile] (/Users/bdw/projects/tornado/src/browser/bower_components/ember/ember-template-compiler.js:643:14)
    at TemplateCompiler.processString (/Users/bdw/projects/tornado/src/browser/node_modules/ember-cli-htmlbars/index.js:50:59)
```

**Comment by oneeman** [comment]
According to the HTML spec, https://html.spec.whatwg.org/multipage/syntax.html#tag-open-state, `<--` should be a parse error, since the `<` indicates the start of a tag and the `-` is not valid for a tag name.  HTMLBars is not handling this correctly, in that it's not throwing an error right there. Regardless, the markup shown is not valid.  You need to escape those characters (e.g. `&lt;` instead of `<`, since they have special meaning in html.

**Comment by mixonic** [comment]
cross-post from https://github.com/emberjs/ember.js/issues/10477

**Comment by oneeman** [comment]
Ah, got it :-)

**Comment by krisselden** [comment]
this should be reported and discussed here https://github.com/tildeio/simple-html-tokenizer/issues
